"""Stats Page Customizer add-on.

Customizes the stats page to remove the '1 year' option and default to 'All time'.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any, Dict, List

try:
    from aqt import gui_hooks, mw
    from aqt.qt import QAction, QDialog, QTimer, QVBoxLayout, QUrl
    from aqt.stats import DeckStats, NewDeckStats
    from aqt.utils import qconnect, showInfo
    from aqt.webview import AnkiWebView
except Exception:  # pragma: no cover - only when run outside Anki
    gui_hooks = None  # type: ignore
    DeckStats = None  # type: ignore[misc,assignment]
    NewDeckStats = None  # type: ignore[misc,assignment]
    AnkiWebView = Any  # type: ignore[misc,assignment]
    QTimer = None  # type: ignore[misc,assignment]
    mw = None  # type: ignore[assignment]
    QAction = None  # type: ignore[assignment]
    QDialog = None  # type: ignore[assignment]
    QVBoxLayout = None  # type: ignore[assignment]
    QUrl = None  # type: ignore[assignment]

    def qconnect(*args: Any, **kwargs: Any) -> None:  # type: ignore[override]
        return None

    def showInfo(*args: Any, **kwargs: Any) -> None:  # type: ignore[override]
        return None

JS_CODE = ""

JS_INJECT_PATH = Path(__file__).with_name("injected.js")
ADDONS_ROOT = Path(__file__).resolve().parent.parent
# Load stats from data/anki/ directory (single source of truth for web terminal)
DATA_ROOT = ADDONS_ROOT / "data" / "anki"
CUSTOM_STATS_HTML = ADDONS_ROOT / "index.html"
# Web terminal uses full data (generated by make fetch)
CUSTOM_STATS_JSON = DATA_ROOT / "custom_stats_data.json"
# Add-on uses separate 30-day file (generated on Anki open, git-ignored)
CUSTOM_STATS_30D_JSON = DATA_ROOT / "custom_stats_30d.json"
FUTURE_DUE_DAYS = 30
MATURE_INTERVAL_DAYS = 21

_custom_stats_dialog: Any = None
_custom_stats_action: Any = None

def _log(message: str) -> None:
    """Append debug info to a log file next to this add-on."""

    try:
        log_path = Path(__file__).with_name("stats_customizer.log")
        log_path.parent.mkdir(parents=True, exist_ok=True)
        with log_path.open("a", encoding="utf-8") as fh:
            fh.write(message + "\n")
    except Exception:
        pass


def _load_injected_js() -> str:
    """Load the stats injection script from disk."""

    if JS_INJECT_PATH.exists():
        try:
            code = JS_INJECT_PATH.read_text(encoding="utf-8")
            if code.strip():
                _log(f"Loaded injected JS from {JS_INJECT_PATH}")
                return code
        except Exception as err:
            _log(f"Failed to read {JS_INJECT_PATH}: {err}")
    else:
        _log(f"Injected JS missing: {JS_INJECT_PATH}")
    return ""


JS_CODE = _load_injected_js()


def _read_custom_stats_template() -> str | None:
    """Return the index.html template if present."""

    if not CUSTOM_STATS_HTML.exists():
        _log(f"Custom stats template missing: {CUSTOM_STATS_HTML}")
        return None

    try:
        return CUSTOM_STATS_HTML.read_text(encoding="utf-8")
    except Exception as err:  # pragma: no cover - file IO guard
        _log(f"Failed to read {CUSTOM_STATS_HTML}: {err}")
        return None


def _inject_payload_into_html(html: str, payload: Dict[str, Any]) -> str:
    """Inject the computed stats payload into the template."""

    data_json = json.dumps(payload, ensure_ascii=False)
    injection = f"<script>window.customStatsData = {data_json};</script>"
    if "</body>" in html:
        return html.replace("</body>", f"{injection}\n</body>", 1)
    return f"{html}\n{injection}"


def _gather_future_due(days: int = FUTURE_DUE_DAYS) -> List[Dict[str, int]]:
    """Return daily mature/young counts for the next `days` days."""

    max_days = max(0, int(days))
    if not mw or not getattr(mw, "col", None):
        _log("Collection unavailable; future due stats empty.")
        return []

    try:
        today = mw.col.sched.today  # type: ignore[attr-defined]
    except Exception as err:
        _log(f"Failed to determine scheduler day: {err}")
        return []

    rows = mw.col.db.all(  # type: ignore[attr-defined]
        """
        SELECT due - ? AS delta,
               SUM(CASE WHEN ivl >= ? THEN 1 ELSE 0 END) AS mature,
               SUM(CASE WHEN ivl < ? THEN 1 ELSE 0 END) AS young
        FROM cards
        WHERE queue = 2
          AND due BETWEEN ? AND ?
        GROUP BY delta
        ORDER BY delta
        """,
        today,
        MATURE_INTERVAL_DAYS,
        MATURE_INTERVAL_DAYS,
        today,
        today + max_days,
    )

    counts_by_day: Dict[int, Dict[str, int]] = {}
    for delta, mature, young in rows:
        day = int(delta or 0)
        if day < 0 or day > max_days:
            continue
        counts_by_day[day] = {
            "mature": int(mature or 0),
            "young": int(young or 0),
        }

    future_due: List[Dict[str, int]] = []
    for day in range(max_days + 1):
        counts = counts_by_day.get(day)
        future_due.append(
            {
                "day": day,
                "mature": counts["mature"] if counts else 0,
                "young": counts["young"] if counts else 0,
            }
        )

    _log(f"Prepared futureDue data for {len(future_due)} days.")
    return future_due


def _write_custom_stats_payload(payload: Dict[str, Any]) -> None:
    """Persist the JSON payload for the add-on (30-day file, git-ignored)."""

    try:
        CUSTOM_STATS_30D_JSON.write_text(
            json.dumps(payload, ensure_ascii=False, indent=2),
            encoding="utf-8",
        )
        _log(f"Wrote custom stats payload to {CUSTOM_STATS_30D_JSON}")
    except Exception as err:
        _log(f"Failed to write {CUSTOM_STATS_30D_JSON}: {err}")


def _read_custom_stats_payload() -> Dict[str, Any] | None:
    """Read the cached JSON payload from the 30-day file."""

    if not CUSTOM_STATS_30D_JSON.exists():
        _log(f"Custom stats cache not found: {CUSTOM_STATS_30D_JSON}")
        return None

    try:
        content = CUSTOM_STATS_30D_JSON.read_text(encoding="utf-8")
        payload = json.loads(content)
        _log(f"Read custom stats payload from {CUSTOM_STATS_30D_JSON}")
        return payload
    except Exception as err:
        _log(f"Failed to read {CUSTOM_STATS_30D_JSON}: {err}")
        return None


def _build_custom_stats_payload() -> Dict[str, Any]:
    """Compose the payload consumed by index.html.
    
    Tries to read from cache first, regenerates if not available.
    """

    # Try to read from 30-day cache first
    payload = _read_custom_stats_payload()
    if payload is not None:
        return payload

    # Cache miss - generate fresh data
    _log("Cache miss - generating fresh custom stats")
    payload = {"futureDue": _gather_future_due()}
    _write_custom_stats_payload(payload)
    return payload


def _render_custom_stats_html() -> str | None:
    """Load the template and inject the latest stats."""

    template = _read_custom_stats_template()
    if template is None:
        return None
    payload = _build_custom_stats_payload()
    return _inject_payload_into_html(template, payload)


def _clear_custom_stats_dialog() -> None:
    """Drop the dialog reference when it closes."""

    global _custom_stats_dialog
    _custom_stats_dialog = None


def _show_custom_stats_dialog() -> None:
    """Open the stats website in a dialog backed by index.html."""

    global _custom_stats_dialog
    if (
        not mw
        or QDialog is None
        or QVBoxLayout is None
        or AnkiWebView is None
    ):
        _log("Qt dependencies missing; cannot show custom stats dialog.")
        return

    html = _render_custom_stats_html()
    if html is None:
        if showInfo:
            showInfo(
                f"index.html が見つかりません。\n{CUSTOM_STATS_HTML}",
                title="Custom Stats",
            )
        return

    dialog = QDialog(mw)
    dialog.setWindowTitle("Custom Stats Website")
    layout = QVBoxLayout(dialog)
    layout.setContentsMargins(0, 0, 0, 0)
    layout.setSpacing(0)

    web = AnkiWebView(dialog)
    layout.addWidget(web)

    if QUrl is not None:
        web.setHtml(html, QUrl.fromLocalFile(str(CUSTOM_STATS_HTML)))
    else:
        web.setHtml(html)

    dialog.resize(780, 620)
    dialog.show()
    _custom_stats_dialog = dialog

    destroyed = getattr(dialog, "destroyed", None)
    if destroyed and qconnect:
        qconnect(destroyed, lambda *_args: _clear_custom_stats_dialog())


def _on_main_window_did_init(mw_obj: Any | None = None) -> None:
    """Add a Tools menu item that opens the stats website."""

    global _custom_stats_action
    if QAction is None or qconnect is None:
        _log("Cannot create custom stats action; Qt dependencies missing.")
        return

    window = mw_obj or mw
    if not window:
        _log("Cannot create custom stats action; main window unavailable.")
        return

    if _custom_stats_action:
        return

    menu = getattr(getattr(window, "form", None), "menuTools", None)
    if menu is None:
        _log("menuTools missing; skipping custom stats action.")
        return

    action = QAction("Custom Stats Website", window)
    action.setToolTip("Opens addons21/index.html with live Anki stats.")
    qconnect(action.triggered, _show_custom_stats_dialog)
    menu.addAction(action)
    _custom_stats_action = action
    _log("Custom stats Tools action installed.")


def _refresh_custom_stats_cache() -> None:
    """Rebuild the 30-day JSON cache from Anki database."""

    if not mw or not getattr(mw, "col", None):
        _log("Cannot refresh custom stats cache; collection unavailable.")
        return

    # Always regenerate 30-day cache on profile open
    payload = {"futureDue": _gather_future_due()}
    _write_custom_stats_payload(payload)
    future_due = payload.get("futureDue", [])
    _log(f"Custom stats cache refreshed with {len(future_due)} days.")


def _on_profile_did_open(_profile: Any | None = None) -> None:
    _refresh_custom_stats_cache()


def _on_collection_did_load(_col: Any | None = None) -> None:
    _refresh_custom_stats_cache()
def _schedule_js_eval(web: AnkiWebView) -> None:
    """Run the JavaScript a few times to catch async loads."""

    delays = (0, 250, 500, 1000, 2000)
    _log(f"_schedule_js_eval called for web={web} delays={delays}")
    if QTimer is None:
        web.eval(JS_CODE)
        _log("QTimer missing; executed JS once.")
        return

    _log(f"Scheduling JS evals with delays={delays}")
    for delay in delays:
        QTimer.singleShot(delay, lambda w=web: w.eval(JS_CODE))

def _attach_on_load(web: AnkiWebView) -> None:
    """Ensure the JS is injected after the stats page finishes loading."""

    if getattr(web, "_stats_customizer_connected", False):
        _log("webview already connected; skipping attach.")
        return

    _log("Attaching loadFinished hook to stats webview.")
    def _on_load_finished(ok: bool) -> None:
        if ok:
            _schedule_js_eval(web)

    load_finished = getattr(web, "loadFinished", None)
    if load_finished is not None:
        load_finished.connect(_on_load_finished)
        _log("Connected loadFinished signal.")
    else:
        _log("loadFinished signal missing.")

    setattr(web, "_stats_customizer_connected", True)
    _schedule_js_eval(web)


def _on_stats_dialog_will_show(stats_dialog: Any) -> None:
    web = getattr(stats_dialog, "web", None)
    if not web:
        _log("stats_dialog lacks web attribute; skipping.")
        return

    _log("stats_dialog_will_show fired; attaching.")
    _attach_on_load(web)


if gui_hooks and hasattr(gui_hooks, "stats_dialog_will_show"):
    gui_hooks.stats_dialog_will_show.append(_on_stats_dialog_will_show)

if gui_hooks and hasattr(gui_hooks, "main_window_did_init"):
    gui_hooks.main_window_did_init.append(_on_main_window_did_init)

if gui_hooks and hasattr(gui_hooks, "profile_did_open"):
    gui_hooks.profile_did_open.append(_on_profile_did_open)

if gui_hooks and hasattr(gui_hooks, "collection_did_load"):
    gui_hooks.collection_did_load.append(_on_collection_did_load)


def _patch_stats_class(cls: Any) -> None:
    if not cls:
        _log("Stats class missing; cannot patch.")
        return

    original_init = getattr(cls, "__init__", None)
    original_refresh = getattr(cls, "refresh", None)
    if not original_init or not original_refresh:
        _log(f"{cls} lacks __init__ or refresh; cannot patch.")
        return

    if not getattr(original_init, "_stats_customizer_patched", False):
        def _wrapped_init(self: Any, *args: Any, **kwargs: Any) -> None:
            original_init(self, *args, **kwargs)
            web = getattr(self, "web", None)
            _log(
                f"{cls.__name__}.__init__ called; has web={bool(web)}; attrs={dir(self)}"
            )
            if web:
                _log(f"{cls.__name__}.__init__ attaching webview via self.web.")
                _attach_on_load(web)
            else:
                fallback_web = getattr(getattr(self, "form", None), "web", None)
                if fallback_web:
                    _log(f"{cls.__name__}.__init__ attaching webview via form.web.")
                    _attach_on_load(fallback_web)
                else:
                    for attr in ("form", "content", "mw"):
                        val = getattr(self, attr, None)
                        if val is not None:
                            _log(
                                f"{cls.__name__}.{attr} type={type(val)} attrs={dir(val)}"
                            )

        _wrapped_init._stats_customizer_patched = True  # type: ignore[attr-defined]
        cls.__init__ = _wrapped_init  # type: ignore[assignment]
        _log(f"Patched {cls.__name__}.__init__")

    if not getattr(original_refresh, "_stats_customizer_patched", False):
        def _wrapped_refresh(self: Any, *args: Any, **kwargs: Any) -> Any:
            result = original_refresh(self, *args, **kwargs)
            web = getattr(self, "web", None)
            if web:
                _log(f"{cls.__name__}.refresh scheduling JS.")
                _schedule_js_eval(web)
            return result

        _wrapped_refresh._stats_customizer_patched = True  # type: ignore[attr-defined]
        cls.refresh = _wrapped_refresh  # type: ignore[assignment]
        _log(f"Patched {cls.__name__}.refresh")


_patch_stats_class(NewDeckStats)
_patch_stats_class(DeckStats)
